name: Tests and Linting
run-name: Tests and Linting
on: [push]
  # push:
  #   branches:
  #     - master
  #     - release
  # pull_request:
  #   branches:
  #     - master
  #     - release
  #     - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ФИО: "Авруцкий Игорь Алексеевич"
      НОМЕР_ГРУППЫ: "М3111"
    steps:
      - name: Print Information
        run: |
          echo "ФИО: ${{ env.ФИО }}"
          echo "Номер группы: ${{ env.НОМЕР_ГРУППЫ }}"
          echo "Ник на Github: ${{ github.actor }}"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: python -m unittest discover tests
        if: ${{ failure() }}
        continue-on-error: false
      - name: Format Code
        run: black .
